# Generated by Django 2.2.5 on 2019-09-13 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abv', models.FloatField()),
                ('ibu', models.IntegerField()),
                ('style', models.TextField(max_length=100)),
                ('taste_profile', models.TextField(max_length=750)),
                ('container_type', models.CharField(choices=[('T', 'Tap'), ('B', 'Bottle'), ('C', 'Can')], default='T', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
