# Generated by Django 2.2.5 on 2019-09-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_beer_brewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='style',
            field=models.CharField(max_length=100),
        ),
    ]
