# Generated by Django 2.2.5 on 2019-09-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_likerestaurantuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
