# Generated by Django 2.2.5 on 2019-09-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20190918_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='beer',
            unique_together={('name', 'brewer')},
        ),
        migrations.AlterUniqueTogether(
            name='restaurant',
            unique_together={('name', 'location')},
        ),
    ]
