# Generated by Django 2.2.5 on 2019-09-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20190918_1556'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='beer',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='restaurant',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='beer',
            constraint=models.UniqueConstraint(fields=('name', 'brewer'), name='unique beer'),
        ),
        migrations.AddConstraint(
            model_name='restaurant',
            constraint=models.UniqueConstraint(fields=('name', 'location'), name='unique restaurant'),
        ),
    ]
